services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_DB: rawdb
      POSTGRES_USER: raw_user
      POSTGRES_PASSWORD: raw_pass
    volumes:
      - pg-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8085:80"
    depends_on:
      - postgres

  mage:
    image: mageai/mageai
    volumes:
      - mage-data:/home/src
      - .:/app
    ports:
      - "6789:6789"
    command: mage start qb_project

volumes:
  pg-data:
  mage-data:
